name: GitHub Page Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
        
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.83.1'
          extended: true

      - name: Build Hugo
        run: hugo --minify

      - name: Deploy Hugo
        uses: peaceiris/actions-gh-pages@v3
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: blog
          PUBLISH_DIR: ./public
          cname: 10001001.xyz
